version: '3.4'

services:
  ms-sql-server-ms:
    image: mcr.microsoft.com/mssql/server
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "StrongPassword???"
       MSSQL_PID: Express
    ports:
       - "1433:1433"
    container_name: "ms-sql-server-ms"
    networks:
      - ms

  roommicroservice:
    image: ${DOCKER_REGISTRY-}roommicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81
    environment: 
      - SERVICE_PORTS=80
    deploy:
     replicas: 2
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
    container_name: "room_microservice"
    networks:
      - ms

  proxy-ms:
    image: dockercloud/haproxy
    ports: 
      - "80:80"
    environment: 
      - BALANCE=leastconn
    deploy:
      placement:
        constraints: [node.role == manager]  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: "haproxy-ms"
    networks: 
      - ms
  
networks: 
  ms:
    driver: overlay